apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cicd-role
  namespace: cicd-team
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - create
  - watch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - create
  - watch
  - delete
