apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2026-03-14T01:01:58Z"
  name: cicd-role
  namespace: cicd-team
  resourceVersion: "233671"
  uid: 0a4d7685-c549-4aa1-8fcb-e36453fd2d05
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - create
  - watch
  - delete
