apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: init-check
          image: busybox:1.35
          command: ['sh', '-c', 'echo "Init container running..."; sleep 5; echo "Init complete!"']
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
      restartPolicy: Always