apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"deployer-role","namespace":"fundtransfer"},"rules":[{"apiGroups":["apps"],"resources":["deployments","replicasets"],"verbs":["get","list","create","update","patch"]},{"apiGroups":[""],"resources":["pods","services"],"verbs":["get","list"]}]}
  creationTimestamp: "2026-03-07T07:28:31Z"
  name: deployer-role
  namespace: fundtransfer
  resourceVersion: "103013"
  uid: 8a9ff013-6c5f-4bb0-9f84-0f9708bab042
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
